version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-django
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/config:/etc/nginx/conf.d/
    depends_on:
      - web
  db:
    image: postgres:latest
    container_name: django-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django-backend
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_ENGINE=${DB_ENGINE}
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db